---
- name: "PlayBook: NetBox - Add Interfaces + LAG Info"
  connection: local
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create interface within Netbox with only required information
      netbox.netbox.netbox_device_interface:
        netbox_url: http://10.0.0.231:8000
        netbox_token: fa8bcce25cdbe307221458c7dbb2cb5227459484
    - name: Create LAG with several specified options
      netbox_device_interface:
        netbox_url: http://10.0.0.231:8000
        netbox_token: fa8bcce25cdbe307221458c7dbb2cb5227459484
        data:
          device: test100
          name: port-channel1
          type: Link Aggregation Group (LAG)
          mtu: 1600
          mgmt_only: false
          mode: Access
        state: present
    - name: Create interface and assign it to parent LAG
      netbox.netbox.netbox_device_interface:
        netbox_url: http://10.0.0.231:8000
        netbox_token: fa8bcce25cdbe307221458c7dbb2cb5227459484
        data:
          device: test100
          name: GigabitEthernet1
          enabled: false
          type: 1000Base-t (1GE)
          lag:
            name: port-channel1
          mtu: 1600
          mgmt_only: false
          mode: Access
        state: present
    - name: Create interface and assign it to parent LAG
      netbox.netbox.netbox_device_interface:
        netbox_url: http://10.0.0.231:8000
        netbox_token: fa8bcce25cdbe307221458c7dbb2cb5227459484
        data:
          device: test100
          name: GigabitEthernet2
          enabled: false
          type: 1000Base-t (1GE)
          lag:
            name: port-channel1
          mtu: 1600
          mgmt_only: false
          mode: Access
        state: present